name: molten_navigationbar_flutter
description: An animated bottom navigation bar with many parameters to tweak.
version: 2.0.8
homepage: https://github.com/AymanProjects/Molten_BottomNavBar_Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  universal_platform: 1.0.0+1


flutter:
